### ISSUE TITLE
VNA Weather

### ISSUE THREAD

**Issue by kaspar-allenbach** [gexclaude/aaregurucli#1]
Okay hie nomau im richtige repo 🤪 für d Akte.

```
+--------------------------------------------------------------+
| Ds wätter      | Morge: 0° / 4mm / 30%   | Sunne             |
| hüt düre Tag   | Nami:  0° / 4mm / 30%   | Räge              |
|                | Abe:   0° / 4mm / 30%   | Gwitter           |
+--------------------------------------------------------------+
| x° = Temp. / Ymm = Rägemängi / Z% = Rägewahrschindlechkeit   | 
+--------------------------------------------------------------+

```

**Comment by kaspar-allenbach** [comment]
API Swissdschörmen Icons: https://github.com/r3to/aare.guru.api/issues/15

**Comment by gexclaude** [comment]
1. Version pushed - swissdschörmen icons chani no nid lese. ha aber bereits füre zuegriff agfragt.

**Comment by gexclaude** [comment]
chaschmr süsch die bärndütsche übersetzige no inekopiere oder so? ha no kei zuegriff uf ds verlinkte repo.

**Comment by kaspar-allenbach** [comment]
- 1 = sunnig
- 2 = zimlech sunnig
- 3 = bewöukt
- 4 = starch bewöukt
- 5 = wärmegwitter
- 6 = starche räge
- 7 = schneefau
- 8 = näbu
- 9 = schneeräge
- 10 = e gutsch
- 11 = liechts rägeli
- 12 = es flöcklet e chli
- 13 = frontgwitter
- 14 = hochnäbu
- 15 = es schneerägeli


Weis nid öb dr christian derzuechunt das scho id API idsboue. Die andere aui si Familievätter und darum aube chli absorbiert :)

**Comment by gexclaude** [comment]
apasst

**Comment by kaspar-allenbach** [comment]
Dr Christian het iz d Wättertexte schüsch o id API Gschribe: http://aareguru.existenz.ch/currentV2.php

**Comment by gexclaude** [comment]
super, lieses itze us dr response.
