### ISSUE TITLE
Doku isch nid aktuell

### ISSUE THREAD

**Issue by boskoop** [gexclaude/aaregurucli#10]
In #8 hetme ds Verhaute apasst. Ize schtimmt d Doku nümm (dr Punkt "Usfüüährig uf dr Kommandozile wie fougt" isch fautsch, wüu me mues ja es Leiout agä):
https://github.com/gexclaude/aaregurucli#grunds%C3%A4tzlechs 

Entweder muesme d Doku apasse, oder denn sötme ds Verhaute vo #8 no chli tjuune.

**Comment by gexclaude** [comment]
@kaspar-allenbach - was dänksch du? mues am chrigu scho rächt gä, es isch haut umständlächer weni no e command mues agä. randomize wie in #8 vorgschlage wäri natürläch o ne variante.

**Comment by kaspar-allenbach** [comment]
Stimmt äuä scho. E default isch vilech scho besser. Randomizing isch äuä zwöi drü mau luschtig, när närvts äuä numeno. Ja, de mach doch wider die ersti var als default und d schribmaschine aus zuesatz.

**Comment by gexclaude** [comment]
top - wirde dr standard aso widr zum default mache und no schnäu nache release

thx @boskoop fürs feedback.

**Comment by gexclaude** [comment]
v0.3.4 released:

https://github.com/gexclaude/aaregurucli/releases/tag/v0.3.4
