### ISSUE TITLE
Prüefe, öbmr e Aare- und Wetter-Azeig im AsciiArt wei mache

### ISSUE THREAD

**Issue by gexclaude** [gexclaude/aaregurucli#14]
Paari kenne http://wttr.in/, das stützt sech uf https://github.com/schachmat/wego. Bi letzterem isches lizenztechnisch mügläch, d AsciiArt Icons ds verwende. Ha no per Mail Rücksprache gno, öb das o ir Ornig wäri und prompt d Rückmeldig becho, dases okay wär. Aso müestmr mau luege, öbr d Wetter-Symbol chönti mappe - u de wäri no es chlyses AsciiArt für d Aare i irgend ere Art cool.

**Comment by kaspar-allenbach** [comment]
I wet eh scho lang mau asci icons probiere. Bruche nume Zit und e Grund.
Ds Problem bi de meischte Wättericonsets isch, dasmese nid so diräkt cha mappe.

**Comment by gexclaude** [comment]
Grund hättemr hie eine - nei i wirdes de churz teste - luege de mau, was wie öpe chönt passe. Eilt nid, aber wäri natürläch schono cool
