### ISSUE TITLE
CLI Design

### ISSUE THREAD

**Issue by kaspar-allenbach** [gexclaude/aaregurucli#2]
Aso i fah hie i däm Codepen mau afa baschtle: https://codepen.io/Sepp/pen/xWbGNq

Gibeder des ok wes ready isch. I baschtle äuä am mänti no chli aber när isch de äuä oscho bau guet.

**Comment by gexclaude** [comment]
<img width="605" alt="screen shot 2018-03-09 at 20 35 00" src="https://user-images.githubusercontent.com/416252/37226234-9473ab92-23d9-11e8-8818-0304abe1e445.png">

**Comment by gexclaude** [comment]
Has scho mau nachezoge, unger angerem fehlerhandling verbesseret, alignments gmacht, progress bar breiti apasst und ds "design" aktualisiert.

**Comment by gexclaude** [comment]
`brew upgrade aareguru`

`aareguru`

**Comment by kaspar-allenbach** [comment]
Dasch ja eigetlech scho tiptop.

Ds einzige isch no ds Grau das funktioniert nid uf wisse terminals

![bildschirmfoto 2018-03-10 um 18 12 26](https://user-images.githubusercontent.com/762213/37244830-d5f52cde-248e-11e8-868e-00aef703a68f.png)

Wo ischdä link zu dene Farbbispiu?

**Comment by kaspar-allenbach** [comment]
Mach doch ds Logo ono Blau, grad ds gsamte.
![bildschirmfoto 2018-03-10 um 18 16 28](https://user-images.githubusercontent.com/762213/37244854-4d671c0a-248f-11e8-9d36-41326e52ad4c.png)

**Comment by gexclaude** [comment]
https://github.com/logrusorgru/aurora

Aber äbe, d farbe chöi überstüret werde. Vilich machi de no e option, d usgab oni farbcode ds mache

**Comment by kaspar-allenbach** [comment]
Mach se doch d Brun d rägewahrschindlechkeit. När findis tiptop

**Comment by gexclaude** [comment]
Has uf Bruun gwechslet. Ds unicode emoji usem footer hani entfernt, das die wenigste terminals scho ungerstütze.

Da d Farbe je nach Terminal nid guet si (bspw. ds logo in blauer schrift in powershell mit blauem hintergrund), chame mit "--ohni-faarb" / "-o" ds Färbe grad ganz usschalte.
