### ISSUE TITLE
Designschiebereien

### ISSUE THREAD

**Issue by kaspar-allenbach** [gexclaude/aaregurucli#3]
![bildschirmfoto 2018-03-12 um 12 43 23](https://user-images.githubusercontent.com/762213/37281939-f7057004-25f2-11e8-9f42-12ade27191ae.png)

- Wassermänge hat etwas zuviele leerzeichen am anfang beim Wert
- `latest öpdate` kommt jetzt gleich nach dem Loader. Sieht nicht so schön aus wenns dann länger als 70 zeichen wird. Kannst du den einfach auf ne neue Zeile nehmen?

**Comment by gexclaude** [comment]
1. Punkt - kann man schieben
2. Punkt - das ist ein Timing Problem, was noch gelöst werden muss. Wenn du es mehrmals ausführst, sollte das nur ab und an auftreten.

**Comment by kaspar-allenbach** [comment]
Ah ja. jetzt gehts. Grad nach dem brew update gings nicht. jetzt aber schon

**Comment by kaspar-allenbach** [comment]
Ah ja und url gärn wider mit 👍

**Comment by gexclaude** [comment]
Das hani mau usgeno, wiu viu terminals unicode nid ungerstütze, de chunts när aus unläserlächs zeiche use.

Mues zersch mau luege, dasi cha usefinge, öb es terminal das ungerstützt oder nid.

**Comment by gexclaude** [comment]
designschiebereie sötis nüm gä. ha ne angeri progress bar component gno. neue release zum teste.

**Comment by kaspar-allenbach** [comment]
Very nice. ha doch nomau es chlises gränn: https://codepen.io/Sepp/pen/xWbGNq

Chönt me nid dr loader +- success uf 1 zile nää und no e +---+ zile derzwüsche de wirds no grad viu süberer
![bildschirmfoto 2018-03-21 um 10 59 40](https://user-images.githubusercontent.com/762213/37703736-fa1c8f88-2cf6-11e8-9857-e558403d47b4.png)

**Comment by gexclaude** [comment]
has ines nöis issue ta: https://github.com/gexclaude/aaregurucli/issues/6
