### ISSUE TITLE
guru CLI nerdery

### ISSUE THREAD

**Issue by kaspar-allenbach** [gexclaude/aaregurucli#5]
Lueg mau das. Das isch ones cli wätterinterface wo chli komplexer isch.
Isch eigetlech e 3 achsigi zitlinie + no agabe via textzeiche. zimlech nice :D 

![bildschirmfoto 2018-03-19 um 17 11 08](https://user-images.githubusercontent.com/762213/37608355-99c5000a-2b9a-11e8-8b88-0db5d6d6c35b.png)

**Comment by gexclaude** [comment]
:) - aber nid sehr intuitiv läsbar :)
