### ISSUE TITLE
value verschoben

### ISSUE THREAD

**Issue by kaspar-allenbach** [gexclaude/aaregurucli#7]
<img width="682" alt="bildschirmfoto 2018-03-22 um 09 18 02" src="https://user-images.githubusercontent.com/762213/37758907-32796f0c-2db2-11e8-841b-28e4df8bb765.png">
D wassertämperatur und mängi si no fautsch gschobe. und so o zwit hinge gägenüber Morge, Nami, Abe

**Comment by gexclaude** [comment]
wo wettischs usrichte? nach links zude LAbels Morge Nami Abe? das geit nur bedingt guet, wiu bspw. d temparatur ja de o hoffentläch 2 stellig wird :) - nach rächts, dases uf de werte vo VNA passt git zmingst bir wassermängi es platz-problem. de müesti der "sirupgleser"-einheit uf ne zuesätzlächi zile schieb.

**Comment by kaspar-allenbach** [comment]
Aso bi 2 stellige zahle wird dr space vordran brucht. Das rütschit nid eifach eis hindere.

Hmmmm.

**Comment by kaspar-allenbach** [comment]
![bildschirmfoto 2018-03-22 um 14 32 01](https://user-images.githubusercontent.com/762213/37773407-cc753a66-2ddd-11e8-9340-d4f237e4bc90.png)
Wie wärs weme e underscore häretuet dasme dinvisuelli linie het. Gseht zwar o nid grad so guet us
gits no irgendes anders zeiche vilech

**Comment by kaspar-allenbach** [comment]
Dasch iz doof. Da blüetet mis grafikerhärz, aber es geit äuä nid anders. Chum. de las eifach so.
