### ISSUE TITLE
Schribmaschinen = Default

### ISSUE THREAD

**Issue by kaspar-allenbach** [gexclaude/aaregurucli#8]
D schribmaschineversion findi dr knüller. Chasch nid die aus standard mache und die anderi irgendwie aus `aareguru plot` ufrüefe?

**Comment by gexclaude** [comment]
oder gar ke default u me mues vo afang a wähle u fingt dbi grad use, dases 2 variante git und nimt die, wo eim besser gfaut? klar, isch när nid so churz zum tippe, aber die meiste wärde öpe d history bruche

**Comment by kaspar-allenbach** [comment]
Jup, findi o guet.

**Comment by gexclaude** [comment]
release wird grad bout

**Comment by boskoop** [comment]
+1 füre aut Default (gfaut mr besser) :smiley: 

Chasch ja süsch füre Default ou dr Plot randomize. Derzeu chönnsch när unger e Hiwiis mache, wie me sech cha die verschidnige Styles usgä oder wie me dr aktuell cha permanänt ufrüefe.
