### ISSUE TITLE
readme assets

### ISSUE THREAD

**Issue by kaspar-allenbach** [gexclaude/aaregurucli#9]
Screenshots si immer guet für ider readme:

Hie no animiert:
[aareguru](http://www.giphy.com/gifs/9P7ml7e3xEmiipZDzA)

![alt text](https://media.giphy.com/media/9P7ml7e3xEmiipZDzA/giphy.gif)

[aareguru schribmaschine](http://www.giphy.com/gifs/WwPb3FYH4wRD5y3Xhj)

![alt text](https://media.giphy.com/media/WwPb3FYH4wRD5y3Xhj/giphy.gif)

**Comment by kaspar-allenbach** [comment]
No eis no chli hackier: https://media.giphy.com/media/5dUteaAiAszFl9iFoD/giphy.gif

**Comment by gexclaude** [comment]
has no chly grösser recorded und is readme ta.
